<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LIN65001941" failures="0" tests="1" name="com.cnhi.tests.BreakdownRepairActivityExecutionForMoreThanOneHour$Demotest" time="374.630" errors="1" timestamp="19 May 2022 08:39:35 GMT" skipped="0">
  <testcase classname="com.cnhi.tests.BreakdownRepairActivityExecutionForMoreThanOneHour$Demotest" name="BreakdownRepairActivityExecutionForMoreThanOneHour" time="374.630">
    <error type="java.lang.Exception">
      <![CDATA[java.lang.Exception
at com.cnhi.pageObjects.JobCardPage.getCreatedAppointmentData(JobCardPage.java:1153)
at com.cnhi.tests.BreakdownRepairActivityExecutionForMoreThanOneHour$Demotest.BreakdownRepairActivityExecutionForMoreThanOneHour(BreakdownRepairActivityExecutionForMoreThanOneHour.java:136)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- BreakdownRepairActivityExecutionForMoreThanOneHour -->
</testsuite> <!-- com.cnhi.tests.BreakdownRepairActivityExecutionForMoreThanOneHour$Demotest -->
